name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main # Adjust this to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          podman build -t my-image:tag .
          podman login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
          podman tag redhat8-lvm:1.0 docker.io/xanubi/redhat8-lvm:1.0
          podman push docker.io/xanubi/redhat8-lvm:tag
